"""diario de trades (notes_journal)

Revision ID: 5629d1ade0ec
Revises: e2bd9deb3038
Create Date: 2026-06-05 22:30:48.330482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5629d1ade0ec'
down_revision = 'e2bd9deb3038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes_journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('asset', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes_journal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_journal_asset'), ['asset'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_journal_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes_journal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_journal_user_id'))
        batch_op.drop_index(batch_op.f('ix_notes_journal_asset'))

    op.drop_table('notes_journal')
    # ### end Alembic commands ###
