"""estrategia do usuario e nota provisoria

Revision ID: a46e7d621728
Revises: 5629d1ade0ec
Create Date: 2026-06-06 03:20:44.403751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a46e7d621728'
down_revision = '5629d1ade0ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brokerage_notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provisional', sa.Boolean(), nullable=False,
                                      server_default=sa.false()))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strategy', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('strategy')

    with op.batch_alter_table('brokerage_notes', schema=None) as batch_op:
        batch_op.drop_column('provisional')

    # ### end Alembic commands ###
