"""estrategias nomeadas (StrategyProfile)

Revision ID: b110654c9410
Revises: cef318334ca8
Create Date: 2026-06-06 14:28:36.067364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b110654c9410'
down_revision = 'cef318334ca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strategy_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_profiles_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_strategy_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('active_strategy_id')

    with op.batch_alter_table('strategy_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_profiles_user_id'))

    op.drop_table('strategy_profiles')
    # ### end Alembic commands ###
