"""analysis_history no diario

Revision ID: cef318334ca8
Revises: a46e7d621728
Create Date: 2026-06-06 13:17:58.086651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef318334ca8'
down_revision = 'a46e7d621728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes_journal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analysis_history', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes_journal', schema=None) as batch_op:
        batch_op.drop_column('analysis_history')

    # ### end Alembic commands ###
