"""layout mercado no usuario

Revision ID: e2bd9deb3038
Revises: 90cf159a77ec
Create Date: 2026-06-05 22:07:47.771246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2bd9deb3038'
down_revision = '90cf159a77ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('layout_mercado', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('layout_mercado')

    # ### end Alembic commands ###
