"""schema inicial

Revision ID: fb65ad5371e5
Revises: 
Create Date: 2026-06-05 02:16:35.186460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb65ad5371e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('b3_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_message', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('brokerage_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('broker', sa.String(length=60), nullable=True),
    sa.Column('note_number', sa.String(length=40), nullable=True),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('corretagem', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('emolumentos', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('taxa_liquidacao', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('taxa_registro', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('iss', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('outras', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('segment', sa.String(length=20), nullable=True),
    sa.Column('daytrade_gross', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('normal_gross', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('irrf_day', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('irrf_swing', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('net_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brokerage_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brokerage_notes_trade_date'), ['trade_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_brokerage_notes_user_id'), ['user_id'], unique=False)

    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('asset', sa.String(length=20), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=True),
    sa.Column('side', sa.String(length=1), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('gross_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['brokerage_notes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trades_asset'), ['asset'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_note_id'), ['note_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_trade_date'), ['trade_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trades_user_id'))
        batch_op.drop_index(batch_op.f('ix_trades_trade_date'))
        batch_op.drop_index(batch_op.f('ix_trades_note_id'))
        batch_op.drop_index(batch_op.f('ix_trades_asset'))

    op.drop_table('trades')
    with op.batch_alter_table('brokerage_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brokerage_notes_user_id'))
        batch_op.drop_index(batch_op.f('ix_brokerage_notes_trade_date'))

    op.drop_table('brokerage_notes')
    op.drop_table('b3_connections')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
